Resources:
  Bucket1:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Base64:
          Ref: Cakes

  Bucket2:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Base64
        Ref: Cakes
