name: cfn-format
version: git
summary: Formats AWS CloudFormation templates.
description: >
  cfn-format is a command line tool that reads an existing AWS CloudFormation template
  and outputs a cleanly-formatted, easy-to-read copy of the same template
  adhering to standards as used in AWS documentation.
  cfn-format can output either YAML or JSON as desired.

license: Apache-2.0

base: core18

grade: stable
confinement: strict

parts:
  cfn-format:
    plugin: go
    source: .
    go-importpath: github.com/awslabs/aws-cloudformation-template-formatter
    go-packages:
      - github.com/awslabs/aws-cloudformation-template-formatter/cmd/cfn-format
    build-packages:
      - gcc
    build-snaps:
      - go

apps:
  cfn-format:
    command: cfn-format
    plugs:
      - home
